/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab04;

import org.apache.commons.math3.geometry.spherical.oned.ArcsSet;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.util.stream.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

class SplittingTest {
    @ParameterizedTest
    @MethodSource("generator")
    void canBalance(String description, int[] nums, boolean expected){
        boolean result = Splitting.canBalance(nums);
        assertEquals(expected, result);
    }

    private static Stream<Arguments> generator(){
        return Stream.of(
                Arguments.of("array null", null, false),
                Arguments.of("array is equal to 0", new int[]{0}, false),
                Arguments.of("check if half value equal to 0", new int[]{4,4,4,4}, true),
                Arguments.of("check if sum%2 value equal to 1", new int[]{10,11}, false),
                Arguments.of("check if sum%2 value equal to 0", new int[]{4,6,8}, false)

        );
    }
}